Commit para pushear
MauriAuat/bootcamp-grupoD-MauricioAuat pull request #2
Opened 2021-05-04 11:21 UTC by MauriAuat

Solicitud para pushear mi rama html

2021-05-25 23:34 UTC, MauriAuat reviewed
HIce mi codigo html desde cero, tratando de aplicar mejor los conceptos para crear una pagina responsive

2021-05-26 10:37 UTC, jchurin requested changes

2021-05-26 10:37 UTC, jchurin commented on .vscode/launch.json
> +{
@MauriAuat no deberias subir este tipo de archivos, ya que son de configuracion del vscode. 
Para evitar subir estos archivos, tenes que crear en el root de tu proyecto un archivo llamado `.gitignore`. 
Dentro de este archivo colocas el path de todas aquellas cosas que quieras evitar subir a git. 
En este caso, queremos evitar todo lo que este dentro de la carpeta .vscode. 
Entonces, para hacer esto, dentro de tu archivo .gitignore colocas:

.vscode/*

2021-05-26 11:22 UTC, jchurin approved these changes

2021-05-26 11:22 UTC, merged